.TH "com.ars.algorithms" 3 "Wed Nov 23 2016" "quantum - computing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ars.algorithms \- 
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBdeutsch\fP"
.br
.ti -1c
.RI "package \fBgrover\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMeasurementPerformer\fP"
.br
.ti -1c
.RI "class \fBQuantumAlgorithms\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for quantum - computing from the source code\&.
