.TH "com.ars.quantumapp.AppTest" 3 "Wed Nov 23 2016" "quantum - computing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ars.quantumapp.AppTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAppTest\fP (String testName)"
.br
.ti -1c
.RI "void \fBtestApp\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Unit test for simple \fBApp\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.ars\&.quantumapp\&.AppTest\&.AppTest (String testName)"
Create the test case
.PP
\fBParameters:\fP
.RS 4
\fItestName\fP name of the test case 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static Test com\&.ars\&.quantumapp\&.AppTest\&.suite ()\fC [static]\fP"

.PP
\fBReturns:\fP
.RS 4
the suite of tests being tested 
.RE
.PP

.SS "void com\&.ars\&.quantumapp\&.AppTest\&.testApp ()"
Rigourous Test :-) 

.SH "Author"
.PP 
Generated automatically by Doxygen for quantum - computing from the source code\&.
