.TH "com.ars.algorithms.MeasurementPerformer" 3 "Wed Nov 23 2016" "quantum - computing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ars.algorithms.MeasurementPerformer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMeasurementPerformer\fP ()"
.br
.ti -1c
.RI "\fBMeasurementPerformer\fP \fBconfigure\fP (\fBQubit\fP resultQubit)"
.br
.ti -1c
.RI "\fBQubit\fP \fBmeasure\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.ars\&.algorithms\&.MeasurementPerformer\&.MeasurementPerformer ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBMeasurementPerformer\fP com\&.ars\&.algorithms\&.MeasurementPerformer\&.configure (\fBQubit\fP resultQubit)"

.SS "\fBQubit\fP com\&.ars\&.algorithms\&.MeasurementPerformer\&.measure ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for quantum - computing from the source code\&.
