.TH "com.ars.quantumapp.App" 3 "Wed Nov 23 2016" "quantum - computing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ars.quantumapp.App \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void com\&.ars\&.quantumapp\&.App\&.main (String [] args)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for quantum - computing from the source code\&.
