.TH "com.ars.gates.QuantumGatesTest" 3 "Wed Nov 23 2016" "quantum - computing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ars.gates.QuantumGatesTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtearDown\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestHGate\fP ()"
.br
.ti -1c
.RI "void \fBtestZGate\fP ()"
.br
.ti -1c
.RI "void \fBtestXGate\fP ()"
.br
.ti -1c
.RI "void \fBtestCNotGate\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void com\&.ars\&.gates\&.QuantumGatesTest\&.setUp () throws Exception"

.SS "void com\&.ars\&.gates\&.QuantumGatesTest\&.tearDown () throws Exception"

.SS "void com\&.ars\&.gates\&.QuantumGatesTest\&.testCNotGate ()"

.SS "void com\&.ars\&.gates\&.QuantumGatesTest\&.testHGate ()"

.SS "void com\&.ars\&.gates\&.QuantumGatesTest\&.testXGate ()"

.SS "void com\&.ars\&.gates\&.QuantumGatesTest\&.testZGate ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for quantum - computing from the source code\&.
