.TH "com.ars" 3 "Wed Nov 23 2016" "quantum - computing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ars \- 
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBalgorithms\fP"
.br
.ti -1c
.RI "package \fBcomplexnumbers\fP"
.br
.ti -1c
.RI "package \fBgates\fP"
.br
.ti -1c
.RI "package \fBquantum\fP"
.br
.ti -1c
.RI "package \fBquantumapp\fP"
.br
.ti -1c
.RI "package \fBqubits\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for quantum - computing from the source code\&.
