.TH "com.ars.qubits.QubitTest" 3 "Wed Nov 23 2016" "quantum - computing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ars.qubits.QubitTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtearDown\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestQubitOne\fP ()"
.br
.ti -1c
.RI "void \fBtestQubitZero\fP ()"
.br
.ti -1c
.RI "void \fBtestConstructorQubitVector\fP ()"
.br
.ti -1c
.RI "void \fBtestToStringMethod\fP ()"
.br
.ti -1c
.RI "void \fBtestEqualsDifferendQubits\fP ()"
.br
.ti -1c
.RI "void \fBtestEqualsDifferentLengthQubits\fP ()"
.br
.ti -1c
.RI "void \fBtestEqualQubits\fP ()"
.br
.ti -1c
.RI "void \fBtestNotEqual\fP ()"
.br
.ti -1c
.RI "void \fBtestValid\fP ()"
.br
.ti -1c
.RI "void \fBtestQubitPlus\fP ()"
.br
.ti -1c
.RI "void \fBtestQubitMinus\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void com\&.ars\&.qubits\&.QubitTest\&.setUp () throws Exception"

.SS "void com\&.ars\&.qubits\&.QubitTest\&.tearDown () throws Exception"

.SS "void com\&.ars\&.qubits\&.QubitTest\&.testConstructorQubitVector ()"

.SS "void com\&.ars\&.qubits\&.QubitTest\&.testEqualQubits ()"

.SS "void com\&.ars\&.qubits\&.QubitTest\&.testEqualsDifferendQubits ()"

.SS "void com\&.ars\&.qubits\&.QubitTest\&.testEqualsDifferentLengthQubits ()"

.SS "void com\&.ars\&.qubits\&.QubitTest\&.testNotEqual ()"

.SS "void com\&.ars\&.qubits\&.QubitTest\&.testQubitMinus ()"

.SS "void com\&.ars\&.qubits\&.QubitTest\&.testQubitOne ()"

.SS "void com\&.ars\&.qubits\&.QubitTest\&.testQubitPlus ()"

.SS "void com\&.ars\&.qubits\&.QubitTest\&.testQubitZero ()"

.SS "void com\&.ars\&.qubits\&.QubitTest\&.testToStringMethod ()"

.SS "void com\&.ars\&.qubits\&.QubitTest\&.testValid ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for quantum - computing from the source code\&.
