.TH "com.ars.quantum.utils.QuantumOperationsTest" 3 "Wed Nov 23 2016" "quantum - computing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ars.quantum.utils.QuantumOperationsTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtearDown\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtestEntangleWithTwoQubitsAllCombinations\fP ()"
.br
.ti -1c
.RI "void \fBtestEntangleWithThreeQubitsAllCombinations\fP ()"
.br
.ti -1c
.RI "void \fBtestApplyXGate\fP ()"
.br
.ti -1c
.RI "void \fBtestApplyXGateWithMatrixParameter\fP ()"
.br
.ti -1c
.RI "void \fBtestCalculateOuterProduct\fP ()"
.br
.ti -1c
.RI "void \fBtestInnerProduct\fP ()"
.br
.ti -1c
.RI "void \fBtestTranspose\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void com\&.ars\&.quantum\&.utils\&.QuantumOperationsTest\&.setUp () throws Exception"

.SS "void com\&.ars\&.quantum\&.utils\&.QuantumOperationsTest\&.tearDown () throws Exception"

.SS "void com\&.ars\&.quantum\&.utils\&.QuantumOperationsTest\&.testApplyXGate ()"

.SS "void com\&.ars\&.quantum\&.utils\&.QuantumOperationsTest\&.testApplyXGateWithMatrixParameter ()"

.SS "void com\&.ars\&.quantum\&.utils\&.QuantumOperationsTest\&.testCalculateOuterProduct ()"

.SS "void com\&.ars\&.quantum\&.utils\&.QuantumOperationsTest\&.testEntangleWithThreeQubitsAllCombinations ()"

.SS "void com\&.ars\&.quantum\&.utils\&.QuantumOperationsTest\&.testEntangleWithTwoQubitsAllCombinations ()"

.SS "void com\&.ars\&.quantum\&.utils\&.QuantumOperationsTest\&.testInnerProduct ()"

.SS "void com\&.ars\&.quantum\&.utils\&.QuantumOperationsTest\&.testTranspose ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for quantum - computing from the source code\&.
