.TH "com.ars.gates.CNotGate" 3 "Wed Nov 23 2016" "quantum - computing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ars.gates.CNotGate \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.ars\&.gates\&.IGate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double [][] \fBgetUnitaryMatrix\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implements the CNOT Gate 
.SH "Member Function Documentation"
.PP 
.SS "double [][] com\&.ars\&.gates\&.CNotGate\&.getUnitaryMatrix ()"
Return the 2D array corresponding to a CNOT gate\&. 
.PP
\fBReturns:\fP
.RS 4
double[][] the corresponding 2D array 
.RE
.PP

.PP
Implements \fBcom\&.ars\&.gates\&.IGate\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for quantum - computing from the source code\&.
