.TH "com.ars.gates.IGate" 3 "Wed Nov 23 2016" "quantum - computing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ars.gates.IGate \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBcom\&.ars\&.gates\&.CNotGate\fP, \fBcom\&.ars\&.gates\&.HGate\fP, \fBcom\&.ars\&.gates\&.ToffoliGate\fP, \fBcom\&.ars\&.gates\&.WiggleGate\fP, \fBcom\&.ars\&.gates\&.XGate\fP, and \fBcom\&.ars\&.gates\&.ZGate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double [][] \fBgetUnitaryMatrix\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface for all types of Quantum Gates\&. 
.SH "Member Function Documentation"
.PP 
.SS "double [][] com\&.ars\&.gates\&.IGate\&.getUnitaryMatrix ()"

.PP
Implemented in \fBcom\&.ars\&.gates\&.WiggleGate\fP, \fBcom\&.ars\&.gates\&.HGate\fP, \fBcom\&.ars\&.gates\&.XGate\fP, \fBcom\&.ars\&.gates\&.ZGate\fP, \fBcom\&.ars\&.gates\&.CNotGate\fP, and \fBcom\&.ars\&.gates\&.ToffoliGate\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for quantum - computing from the source code\&.
