.TH "com.ars.qubits.QubitZero" 3 "Wed Nov 23 2016" "quantum - computing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ars.qubits.QubitZero \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.ars\&.qubits\&.Qubit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQubitZero\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SH "\fBQubitZero\fP"
.PP
.PP
Representation of the qubit |0>=[1,0]\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.ars\&.qubits\&.QubitZero\&.QubitZero ()"
Construct a new \fC \fBQubitZero\fP\fP object\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for quantum - computing from the source code\&.
