.TH "com.ars.algorithms.deutsch.DeutschsAlgorithm" 3 "Wed Nov 23 2016" "quantum - computing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ars.algorithms.deutsch.DeutschsAlgorithm \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.ars\&.algorithms\&.QuantumAlgorithms\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeutschsAlgorithm\fP (double[][] testedFunctionOperator)"
.br
.ti -1c
.RI "\fBDeutschsAlgorithm\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBmeasure\fP ()"
.br
.ti -1c
.RI "boolean \fBisFunctionConstant\fP ()"
.br
.ti -1c
.RI "boolean \fBisFunctionBalanced\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.ars\&.algorithms\&.deutsch\&.DeutschsAlgorithm\&.DeutschsAlgorithm (double testedFunctionOperator[][])"

.SS "com\&.ars\&.algorithms\&.deutsch\&.DeutschsAlgorithm\&.DeutschsAlgorithm ()"

.SH "Member Function Documentation"
.PP 
.SS "void com\&.ars\&.algorithms\&.deutsch\&.DeutschsAlgorithm\&.init ()"

.SS "boolean com\&.ars\&.algorithms\&.deutsch\&.DeutschsAlgorithm\&.isFunctionBalanced ()"

.SS "boolean com\&.ars\&.algorithms\&.deutsch\&.DeutschsAlgorithm\&.isFunctionConstant ()"

.SS "void com\&.ars\&.algorithms\&.deutsch\&.DeutschsAlgorithm\&.measure ()"

.SS "void com\&.ars\&.algorithms\&.deutsch\&.DeutschsAlgorithm\&.run ()"
The following operations are performed: entangle qubitZero (qubitZero |> gateX) |> gateH2 |> f |> gateH2

.SH "Author"
.PP 
Generated automatically by Doxygen for quantum - computing from the source code\&.
