.TH "com.ars.qubits" 3 "Wed Nov 23 2016" "quantum - computing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ars.qubits \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQubit\fP"
.br
.ti -1c
.RI "class \fBQubitMinus\fP"
.br
.ti -1c
.RI "class \fBQubitOne\fP"
.br
.ti -1c
.RI "class \fBQubitPlus\fP"
.br
.ti -1c
.RI "class \fBQubitTest\fP"
.br
.ti -1c
.RI "class \fBQubitZero\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for quantum - computing from the source code\&.
