.TH "com.ars.gates.EGateTypes" 3 "Wed Nov 23 2016" "quantum - computing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ars.gates.EGateTypes \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBE_ToffoliGate\fP"
.br
.ti -1c
.RI "\fBE_HadamardGate\fP"
.br
.ti -1c
.RI "\fBE_XGate\fP"
.br
.ti -1c
.RI "\fBE_ZGate\fP"
.br
.ti -1c
.RI "\fBE_CNotGate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implemented Quantum Gates\&. 
.SH "Member Data Documentation"
.PP 
.SS "com\&.ars\&.gates\&.EGateTypes\&.E_CNotGate"
CNOT Gate 
.SS "com\&.ars\&.gates\&.EGateTypes\&.E_HadamardGate"
Hadamard Gate 
.SS "com\&.ars\&.gates\&.EGateTypes\&.E_ToffoliGate"
Toffoli Gate 
.SS "com\&.ars\&.gates\&.EGateTypes\&.E_XGate"
Pauli-X Gate 
.SS "com\&.ars\&.gates\&.EGateTypes\&.E_ZGate"
Pauli-Z Gate 

.SH "Author"
.PP 
Generated automatically by Doxygen for quantum - computing from the source code\&.
