.TH "com.ars.gates.GatesAbstractFactory" 3 "Wed Nov 23 2016" "quantum - computing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ars.gates.GatesAbstractFactory \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBcom\&.ars\&.gates\&.GateFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract \fBIGate\fP \fBgetGate\fP (\fBEGateTypes\fP id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of a Abstract Factory 
.SH "Member Function Documentation"
.PP 
.SS "abstract \fBIGate\fP com\&.ars\&.gates\&.GatesAbstractFactory\&.getGate (\fBEGateTypes\fP id)\fC [abstract]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for quantum - computing from the source code\&.
