.TH "com.ars.qubits.QubitMinus" 3 "Wed Nov 23 2016" "quantum - computing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ars.qubits.QubitMinus \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.ars\&.qubits\&.Qubit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQubitMinus\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SH "\fBQubitMinus\fP"
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.ars\&.qubits\&.QubitMinus\&.QubitMinus ()"
Construct a new \fC \fBQubitMinus\fP\fP object\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for quantum - computing from the source code\&.
