.TH "C:/Users/Dacian/Desktop/Quantum/Quantum/quantum_computing-master/CONTRIBUTING.md" 3 "Wed Nov 23 2016" "quantum - computing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Dacian/Desktop/Quantum/Quantum/quantum_computing-master/CONTRIBUTING.md \- 
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for quantum - computing from the source code\&.
