.TH "C:/Users/Dacian/Desktop/Quantum/Quantum/quantum_computing-master/quantum/src/main/java/com/ars/gates/IGate.java" 3 "Wed Nov 23 2016" "quantum - computing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Dacian/Desktop/Quantum/Quantum/quantum_computing-master/quantum/src/main/java/com/ars/gates/IGate.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBcom\&.ars\&.gates\&.IGate\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBcom\&.ars\&.gates\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for quantum - computing from the source code\&.
