.TH "md__c_1__users__dacian__desktop__quantum__quantum_quantum_computing-master__c_o_n_t_r_i_b_u_t_i_n_g" 3 "Wed Nov 23 2016" "quantum - computing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1__users__dacian__desktop__quantum__quantum_quantum_computing-master__c_o_n_t_r_i_b_u_t_i_n_g \- CONTRIBUTING 

.IP "1." 4
Please use the issues to notify me about found bugs or about features that should be add\&. 
.PP

